### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by aaronwlee** [timreichen/Bundler#1]
Hi, your project is fantastic!
But, I've got this error when I used the jspm.dev CDN
```
error: Uncaught TypeError: Path must be a string. Received undefined
  CHAR_UPPERCASE_A,
  ^
    at assertPath (https://deno.land/std/path/_util.ts:7:3)
    at join (https://deno.land/std/path/win32.ts:272:5)
    at Bundler.bundle (bundler.ts:212:13)
    at async Command._fn (cli.ts:113:7)
```

here is an example code

path: src/deps.ts
```ts
// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
import React from "https://jspm.dev/react@16.13.1";

// @deno-types="https://deno.land/x/types/react-dom/v16.13.1/server.d.ts"
import ReactDOMServer from "https://jspm.dev/react-dom@16.13.1/server";

// @deno-types="https://deno.land/x/types/react-dom/v16.13.1/react-dom.d.ts"
import ReactDOM from "https://jspm.dev/react-dom@16.13.1";


export {
  React,
  ReactDOM,
  ReactDOMServer,
};
```

path: src/index.tsx
```ts
import { React, ReactDOM } from "./deps.ts";

console.log(React, ReactDOM)
```

and started bundle with this command.

```
denobundler bundle --name index.js .\src\index.tsx
```

Thanks :)

**Comment by timreichen** [comment]
Thank you for your kind words!

Bundler only scans files with ```ts``` and ```js``` extensions. I added ```tsx``` and ```jsx```, so it should work now. You might need to reinstall bundler and add ```--reload``` when bundling.

**Comment by aaronwlee** [comment]
Things are working well! 

But some dependencies are not connecting well, it generates some empty files and the main file is connecting to the empty file.

**Comment by timreichen** [comment]
Which deps are they? Do you have an example rep or project?

**Comment by aaronwlee** [comment]
An example that I gave you had this issue. Please try it and take a look at the files.

**Comment by aaronwlee** [comment]
Sorry. It seems to be a Deno bug. Re-installing Deno will fix it.
