### ISSUE TITLE
Provide Source

### ISSUE THREAD

**Issue by khrome83** [timreichen/Bundler#15]
Deno.bundle seems to allow providing direct source strings. I was curious if something like that could be done with this. 

I have my own parser/compiler I am building for a template language. And my thought was to pass all script contents that any component used into a Bundler of sorts. 

Deno.bundle seems to solve for ES modules, but I am trying to find a solution for legacy browsers, compiling TS, or running Babel.

**Comment by timreichen** [comment]
I am not sure exactly what you mean. Do you suggest the Bundler API to take a string as input for transpilation?

**Comment by khrome83** [comment]
So, since there is no script file as entry points in my case, the idea would be to provide the raw source as a strings for all script contents inside the template language. 

To pain the picture. 

The template language can take components. Each component can implement script blocks as they see fit for client side code. The template language is only run in deno with the goal of shipping html. 

So if I passed all strings as possible entry points, the idea would be to concat those together and also bundle any dependencies. Dependencies could be external from the Templar language and done in plain JS/TS. 

Does that make sense?

**Comment by timreichen** [comment]
So you mean to bundle together multiple entry points?
This is not possible because files might have same named exports.
What you can do however is make a bundle like this
```ts
import "./entry1.ts"
import "./entry2.ts"
```
and set that as the entry. But this should also possible with Deno.bundle.

**Comment by khrome83** [comment]
We are not referring to the same thing. 

What I am saying is you do not have files to bundle in my scenario.

Or atleast not a good set of them. Any imports they refer to can be. But I am saying I need to provide a set of raw source strings. I can't give a file name because you have nothing to parse as the entry point. 

But if I give a raw source string, can you start bundling from there? 

As far as multiple entry points, it's more like a concatenation. None of those raw source strings can import each other, since they are in the template language.

**Comment by khrome83** [comment]
Sorry, my last response was from my mobile phone. Let me try to build a better example.

src/components/file-a
```html
<script>
 import y from 'something.ts';
 let x = "foo";
 y(x)
</script>
```


src/components/file-b
```html
<script>
 import y from 'something.ts';
 let x = "bar";
 y(x)
</script>
```

The basic idea is that I want to pass the contents of the file-a, and file-b if they are used on the same page.

Since these are template files, they are not something parsable I would assume without a lot of effort. So the idea would be to pass the raw strings of the script blocks insides. The bundler would concat, and prevent name collisions and deal with resolving imports. Basically everything that bundlers already do.

I know if this was rollup or webpack, this is the basic concept of how they work today when working with React, Svelte, or Vue. 

Does that help clarify the issue?

**Comment by timreichen** [comment]
Ok, I think it is a good idea to have Bundler API provide a way to transpile/bundle strings instead of files.

Until then: It seems to me what you want is doable with ```Deno.bundle```:
```ts
const [diagnostics, emit] = await Deno.bundle("/index.ts", {
  "/index.ts": `import "./entry1.ts"; import "./entry2.ts";`,
  "/entry1.ts": `import y from "./something.ts"; let x = "foo"; y(x);`,
  "/entry2.ts": `import y from "./something.ts"; let x = "bar"; y(x);`,
  "/something.ts": `export default function (x: string) { console.log(x); }`,
})
```

**Comment by khrome83** [comment]
Correct. Yeah and I was thinking of maybe a similar interface. 

The issue with Deno.bundle is that it will only do ES modules and I don't think there is a path for older browsers. 

It's why I raised this. 

I was also looking at ESBUILD which has a WASM browser api, that is way faster than rollup, (100x) but it does not bundle with WASM you would need the go executable.

**Comment by timreichen** [comment]
0.2.0 is out. It now takes an InputMap and an OutputMap for bundling.
