### ISSUE TITLE
No output File

### ISSUE THREAD

**Issue by ebebbington** [timreichen/Bundler#20]
was testing out bundler, and no out file is being created, or maybe it's being creating in another dir (still a bug)

```typescript
// a.ts
import * as colours from "https://deno.land/std/fmt/colors.ts"

console.log(colours.red('hello'))
```
```
$ deno install --unstable --allow-read --allow-write --allow-net --allow-env --name bundler https://deno.land/x/bundler/cli.ts
$ bundler bundle a.ts=a.js
```

**Comment by timreichen** [comment]
The default outDir is `dist`. So it should have created a `dist/a.js`. Does that exist?

**Comment by ebebbington** [comment]
Aha it does - turns out the project i was testing it in was ignoring the `./dist` dir xD
