### ISSUE TITLE
Failure When Using deno.land Imports

### ISSUE THREAD

**Issue by ebebbington** [timreichen/Bundler#21]
```typescript
// a.ts
import { red } from "https://deno.land/std@0.73.0/fmt/colors.ts"
console.log(red('hello'))
```
```
$ bundler bundle a.ts=a.js
```
```
// index.html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
<script src="dist/a.js"></script>
</body>
</html>
```

Open the web page, or do `node dist/a.js`, and see `Cannot read property 'red' of undefined'

**Comment by timreichen** [comment]
I think you meant the url to be „ https://deno.land/std@0.73.0/fmt/colors.ts“

**Comment by ebebbington** [comment]
Oops my bad, same result when it's corrected

**Comment by timreichen** [comment]
are you using the latest version (0.3.4)? I successfully ran the same code.
When you rerun try using `--reload` to redo the cache and create a fresh bundle.

**Comment by ebebbington** [comment]
Nah i still get the same error, for reference i did:

```
$ deno install -f --unstable --allow-read --allow-write --allow-net --allow-env --name bundler --reload https://deno.land/x/bundler/cli.ts
```

Re ran the bundler command, and opened up the html file again

**Comment by timreichen** [comment]
Hmm, what platform are you using?
Can you do a repo?

**Comment by ebebbington** [comment]
MacOS, and sure gimme a sec 👍

**Comment by ebebbington** [comment]
It was good you mentioned making a new repo, because it seems to work now, guessing something was causing a problem in the old dir
