### ISSUE TITLE
esm.sh types error

### ISSUE THREAD

**Issue by ije** [timreichen/Bundler#23]
maybe you can try to remove the `x-typescript-types` header with `no-check` option:

```javascript
import presetEnv from "https://esm.sh/postcss-preset-env@6.7.0?no-check"
```

**Comment by timreichen** [comment]
Thank you for your great suggestion. That works and is a really nice solution.

**Comment by ije** [comment]
i am still looking for a solution to transform DTS like `declare module "postcss-preset-env" { ... }` to work in Deno.
