### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by alfredosalzillo** [timreichen/Bundler#29]
Installing bundler I'm getting this error

```
error: Import 'https://esm.sh/postcss-preset-env@6.7.0?no-check' failed: 500 Internal Server Error
```

**Comment by timreichen** [comment]
Thank you for reporting. Seems like the problem might be on the `esm.sh` side. I opened an issue (https://github.com/postui/esm.sh/issues/30).

**Comment by ije** [comment]
@alfredosalzillo fixed, please try again, thanks!

**Comment by ije** [comment]
@timreichen can you please try to remove the `no-check` flag? seems the type is correct now:

```js
import "https://esm.sh/postcss-preset-env@6.7.0"
```

**Comment by timreichen** [comment]
@ije Yes that works now, thanks!
