### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by disyam** [timreichen/Bundler#30]
i try to install with this command:
`deno install --unstable --allow-read --allow-write --allow-net --allow-env --name bundler https://deno.land/x/bundler/cli.ts`

but got this error:
`error: TS2352 [ERROR]: Conversion of type 'string | symbol' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'symbol' is not comparable to type 'number'.
    return getArguments()[prop as number];
                          ~~~~~~~~~~~~~~
    at https://deno.land/std@0.87.0/node/process.ts:58:27`

deno version : 1.8.2
os : fedora 33

**Comment by timreichen** [comment]
Hello, I think the problem has nothing to do with bundler itself but with the `std/node` module in correlation with the platform you are using. You might want to open an issue [here](https://github.com/denoland/deno_std/issues).
