### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by aegooby** [timreichen/Bundler#31]
Gives error:
```
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://cdn.esm.sh/v35/sha.js@2.4.11/deno/sha.js.js
  MediaType: Json
```

Seems to be because of the extension (.js.js) at the end is wrong; when visiting the webpage https://cdn.esm.sh/v35/sha.js@2.4.11/deno/sha.js, the file is fine.

**Comment by timreichen** [comment]
Can you post, how to reproduce it? The js.js file does indeed not exist, and the error is not created by bundler itself.

**Comment by aegooby** [comment]
Simply ran the install command in the README:
```
deno install --unstable --allow-read --allow-write --allow-net --allow-env --name bundler https://deno.land/x/bundler/cli.ts
```
My Deno version is 1.8.3

**Comment by timreichen** [comment]
I think there is a problem with esm.sh, probably needs an issue there. I will look into that tomorrow.

**Comment by aegooby** [comment]
So the previous issue has been fixed (thank you for the work on that by the way!) but it seems like a new one has cropped up:
```
Check https://deno.land/x/bundler/cli.ts
error: Uncaught SyntaxError: The requested module '/v36/caniuse-lite@1.0.30001207/deno/caniuse-lite.js' does not provide an export named 'feature'
    at <anonymous> (https://cdn.esm.sh/v36/postcss-preset-env@6.7.0/deno/postcss-preset-env.js:1:5180)
```
When running the same install command. Unfortunately doesn't work when setting the Deno `--no-check` flag either.

**Comment by timreichen** [comment]
Yeah, there is something weird going on with esm.sh server which does has nothing to do with deno nor bundler. Hopefully @ije fixes it soon. I [proposed](https://github.com/postui/esm.sh/issues/46#issuecomment-814280900) a versioned esm.sh to avoid sudden breaks.

**Comment by ije** [comment]
oh, sorry i'm tryng to fix it since i changed a lot things...
in v37, i can install the bundler command normally, but when i try to bundle a file, i got an strage error: 
<img width="670" alt="Screenshot 2021-04-07 at 04 02 13" src="https://user-images.githubusercontent.com/2883484/113771521-0ada6a80-9756-11eb-9f3b-b4042270cabb.png">

**Comment by timreichen** [comment]
I think I saw that error before when typescript transpiles to ES5 target or lower. Maybe setting the --config will help? I am completely reworking the transpilation process in bundler to get rid of systemjs and allow top level await to function as expected, so I am not sure anymore what defaults are set.

**Comment by aegooby** [comment]
With esm.sh v38 installation works fine, but running it gives error,
```
error: Uncaught Error: [esm.sh] Unsupported nodejs builtin module "inspector"
throw new Error("[esm.sh] " + "Unsupported nodejs builtin module \"inspector\"");
      ^
    at https://cdn.esm.sh/_error.js?type=unsupported-nodejs-builtin-module&name=inspector:2:7
```

**Comment by timreichen** [comment]
@aegooby I think this is not relevant to bundler’s code but to esm.sh. Could you post that on the esm.sh issue?

**Comment by timreichen** [comment]
Resloved by https://github.com/postui/esm.sh/issues/46. Should now work as expected
