### ISSUE TITLE
how to disable export default in final js bundle file?

### ISSUE THREAD

**Issue by buttercubz** [timreichen/Bundler#35]
The reason is that in the browser I am forced to use `type="module"` even though I am not importing or exporting anything.

`see`
![image](https://user-images.githubusercontent.com/47539192/115928689-8a558280-a454-11eb-86cc-d1e5730e134e.png)

**Comment by timreichen** [comment]
I added no module script support for 0.6.6. Does it work as intended now?

**Comment by buttercubz** [comment]
thanks for your quick response, works fine
