### ISSUE TITLE
Use as a api

### ISSUE THREAD

**Issue by buttercubz** [timreichen/Bundler#36]
I am currently using bundler to compile to production ([see](https://github.com/crewdevio/Snel/blob/a2cf09eb07aa15370029e22222ff4c4752eeff9c/src/cli/create.ts#L34)), but I would like to be able to use it without installing bundler as a cli like [rollup](https://github.com/crewdevio/Snel/blob/a2cf09eb07aa15370029e22222ff4c4752eeff9c/compiler/build.ts#L40)

**Comment by timreichen** [comment]
This is already possible. There is a [server example](https://github.com/timreichen/Bundler/tree/master/examples/server) on how to use it as an API. But be warned: The Bundler API is not yet on v1.0 and probably is going to have breaking changes in the future, so be careful when using for production.

**Comment by buttercubz** [comment]
oh, grace hadn't seen that example
