### ISSUE TITLE
API: bundle function don't write output assets 

### ISSUE THREAD

**Issue by buttercubz** [timreichen/Bundler#37]
https://user-images.githubusercontent.com/47539192/116892051-6b49b400-abfd-11eb-836b-9e1f4d0fd4a8.mp4

**Comment by buttercubz** [comment]
I was looking at the [cli](https://deno.land/x/bundler@0.7.0/cli.ts#L205) file and I see that the bundle function does not write, in the same way, creating a section within the readme where the behavior of the api is explained would be excellent

**Comment by timreichen** [comment]
closed in favour of https://github.com/timreichen/Bundler/issues/38
