### ISSUE TITLE
bundler and bundler api are not emiting javascript output

### ISSUE THREAD

**Issue by buttercubz** [timreichen/Bundler#42]
Javascript files are not emitting in bundler 0.7.2 neither by the cli or by the api, in previous versions this does not happen.

https://user-images.githubusercontent.com/47539192/121544543-ced2b880-c9d7-11eb-8910-065eb469fa5d.mp4

the html index comes from the base example created by snel

**Comment by timreichen** [comment]
That is unexpected behaviour. I will check that on the weekend.

**Comment by buttercubz** [comment]
> That is unexpected behaviour. I will check that on the weekend.

any update?

**Comment by timreichen** [comment]
I added tests for javascript files. Should be fixed now with 0.8.0.
