### ISSUE TITLE
Feature Request: Support circular dependencies

### ISSUE THREAD

**Issue by voltrevo** [timreichen/Bundler#49]
These sources are perfectly valid TypeScript:

```ts
// A.ts
import { B } from "./B.ts";

export class A {
  static makeB() { return new B(); }
}
```

```ts
// B.ts
import { A } from "./A.ts";

export class B {
  static makeA() { return new A(); }
}
```

```ts
// example.ts
import { A } from "./A.ts";

console.log(A.makeB());
```

You can run them in deno:
```
$ deno run example.ts
B {}
```

You can also run them in node, it's supported by other bundlers, etc.

However, in Bundler, it generates:

```
Circular Dependency A.ts → B.ts → A.ts
Error: Circular Dependency
```

I imagine this is a known issue, and, don't get me wrong, I love this project. Still, I want this issue to exist so that you're aware this feature is desired.

I actually think it's kinda fundamentally necessary even if it may be a good idea to avoid it when you can.

Even without that though, not having this feature severely limits the community libraries that can be used when using Bundler.

**Comment by timreichen** [comment]
Hi, this is a known issue. Bundler wraps all modules in an async iife function to allow top level await code in browsers that do not support it yet. This doesn't work if there are circular dependencies, therefore an error is thrown for precaution.
Circular dependencies are handled by esm, so this problem will be solved once all major browsers have tla support and the wrapping is no longer needed. As of today we are waiting for safari to catch up: https://caniuse.com/?search=top%20level%20await

**Comment by voltrevo** [comment]
Hi. Thanks for the info. Does that mean the chunking logic will just be updated to ensure that circular references are always spread across different chunks? (Since if you use top-level-await and have a single file you could just wrap the whole thing in an async iife right?)

**Comment by timreichen** [comment]
Circular dependencies should be fixed now.
