### ISSUE TITLE
Bundler fails to run when trying to import `acorn` via `terser`

### ISSUE THREAD

**Issue by rotu** [timreichen/Bundler#53]
Bundler is failing to run with a SyntaxError when trying to import `acorn` via `terser`.

Possibly related to https://github.com/terser/terser/issues/1002

```
deno run --unstable --allow-all -r https://deno.land/x/bundler/spa_server_cli.ts

...

Check https://deno.land/x/bundler/spa_server_cli.ts
error: Uncaught SyntaxError: The requested module '/v51/acorn@8.5.0/deno/acorn.js' does not provide an export named 'default'
    at <anonymous> (https://cdn.esm.sh/v51/terser@5.7.1/deno/terser.js:2:172)
```

```
deno --version
deno 1.14.0 (release, aarch64-apple-darwin)
v8 9.4.146.15
typescript 4.4.2
```

**Comment by timreichen** [comment]
That seems to be a problem on the `esm.sh` side.

**Comment by ije** [comment]
@rotu i will fix this asap!

**Comment by ije** [comment]
@rotu can you pls try again?

**Comment by ije** [comment]
@timreichen can you please add some testings in esm.sh ensure this not happen again? for example: https://github.com/alephjs/esm.sh/blob/master/test/deno/common/terser.test.ts

**Comment by rotu** [comment]
Thank you, @ije! I can verify this is fixed
