### ISSUE TITLE
Bundler misinterprets Windows path as a url

### ISSUE THREAD

**Issue by rotu** [timreichen/Bundler#58]
When trying to use the CLI on Windows with a relative path, it misunderstands the file path as a URL, failing with a confusing error message.

I think the issue is here https://github.com/timreichen/Bundler/blob/a76c440a38c3e582ccd46d0e806573434b21631d/_util.ts#L9-L16

> C:\Users\dan\Desktop>deno run -A --unstable https://raw.githubusercontent.com/timreichen/Bundler/restructure/cli.ts bundle ./test.html
> file not found: c:\Users\dan\Desktop\test.html
> error: Uncaught (in promise) TypeError: scheme 'c' not supported
>         return await fetch(input)
>                      ^
>     at Object.opSync (deno:core/01_core.js:170:12)
>     at opFetch (deno:ext/fetch/26_fetch.js:71:17)
>     at mainFetch (deno:ext/fetch/26_fetch.js:221:61)
>     at deno:ext/fetch/26_fetch.js:458:11
>     at new Promise (<anonymous>)
>     at fetch (deno:ext/fetch/26_fetch.js:425:20)
>     at HTMLPlugin.readSource (https://raw.githubusercontent.com/timreichen/Bundler/restructure/plugins/file/text_file.ts:16:22)
>     at HTMLPlugin.createSource (https://raw.githubusercontent.com/timreichen/Bundler/restructure/plugins/plugin.ts:139:31)
>     at HTMLPlugin.createAsset (https://raw.githubusercontent.com/timreichen/Bundler/restructure/plugins/html/html_plugin.ts:36:31)
>     at Bundler.createAsset (https://raw.githubusercontent.com/timreichen/Bundler/restructure/bundler.ts:60:36)

**Comment by rotu** [comment]
I can also confirm this works correctly when invoked as either of:

`deno run -A https://raw.githubusercontent.com/timreichen/Bundler/restructure/cli.ts bundle "file://C:\Users\dan\Desktop\test.html"`
`deno run -A https://raw.githubusercontent.com/timreichen/Bundler/restructure/cli.ts bundle "\\.\C:\Users\dan\Desktop\test.html"`

**Comment by timreichen** [comment]
I added an extra check for filepaths and status checks for windows. Can you check if it works now as expected on the main branch?

**Comment by rotu** [comment]
No dice. Did you check in your changes? The `isURL` function *still* returns true for Windows file paths, leading to the same improper fetch call.

**Comment by timreichen** [comment]
https://github.com/timreichen/Bundler/pull/61 might fix the problem. But there are not tests atm that run cli.ts with args and flags. cli.ts needs a cli_test.ts file with cli tests to catch these kind of bugs.
