### ISSUE TITLE
Suggestion: swc

### ISSUE THREAD

**Issue by timreichen** [timreichen/Bundler#6]
Deno uses ```swc``` transpiler. Replace ```ts``` transpiler with rust ```swc``` deno plugin.

**Comment by ije** [comment]
wish deno `openPlugin` become stable ASAP

**Comment by timreichen** [comment]
possible solution once feature-rich and stable: https://github.com/nestdotland/deno_swc/actions

**Comment by andrewc910** [comment]
Any progress on this?

**Comment by timreichen** [comment]
Not yet sadly. Seems like the deno_swc rep hasn't been updated for months and before a switch, I would need some help to determine if all features are available. For example: How would transforming ts code to system (like in `module:system` in ts compilerOptions) work with swc? I never used swc myself and would need some help on this.

**Comment by shadowtime2000** [comment]
Any reason for not using `Deno.emit` with not setting `bundle` to just transpile the code @timreichen?

**Comment by timreichen** [comment]
@shadowtime2000 A few reasons:
1. `Deno.emit` will bundle all resources together into one file. If there are multiple entry files that share dependencies, there will be duplicate code. I think a better way in browsers is to allow for code splitting explained [here](https://github.com/timreichen/Bundler#smart-splitting), which is not currently possible with `Deno.emit`.
2. Since this bundler supports different file types such as images, css and html etc., the correct output paths need to be injected, which is done by a typescript transformer. `Deno.emit` does not allow transformer hooks as of now.
3. `Deno.emit` does not use system modules anymore, though browsers do not yet support top level await. 

But I am playing with the idea of using `Deno.bundle` if none of the upper arguments apply.

**Comment by shadowtime2000** [comment]
@timreichen Makes sense, but you can disable bundling with `Deno.emit` so that it only transpiles TS.

**Comment by timreichen** [comment]
Yes but I need the ts compiler to be able to do more than just transpile ts to js. There is a lot of ast manipulation going on for injecting paths and import statements etc.
What would the advantage of using `Deno.emit` be? I still would need to use a ast walker parallel to that.

**Comment by shadowtime2000** [comment]
@timreichen Fair point. I wasn't arguing with you, just pointing out that your first point about bundling didn't work 😄

**Comment by timreichen** [comment]
No that was a good question. I asked on deno discord about a transfomer option for `Deno.emit`, seems to have gone lost. I would like to use either `Deno.emit` rather than the ts module, so if that became a thing I'd gladly switch.

**Comment by timreichen** [comment]
> possible solution once feature-rich and stable: https://github.com/nestdotland/deno_swc/actions

After tests it seems that wasm based deno-swc is slower than the ts module. Closing this issue for now until more options are available. Feel free to reopen again.
