### ISSUE TITLE
Guide for create pluging 

### ISSUE THREAD

**Issue by elycheikhsmail** [timreichen/Bundler#76]
How ceate custum plugin ?

**Comment by timreichen** [comment]
by creating a class which extends the abstract class `Plugin`. Depending on your need you can also extend `FilePlugin` or `TextFilePlugin`.
Then it can be used as described here: https://github.com/timreichen/Bundler#advanced-example-
See the other plugins as examples.

**Comment by elycheikhsmail** [comment]
thank you
