### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by timreichen** [timreichen/Bundler#9]
create proper documentation, update readme

**Comment by itays123** [comment]
I think I can do this, forking your repo...

**Comment by itays123** [comment]
I'm gonna need to understand a few things:

1. In your documentation the purpose wasn't very clear to me... you are trying to make another version of `deno bundle`, that includes css bundling and React.js as I see in your 5th example, am I right?

2. provide real-world examples. not just `console.log`s and imports.

**Comment by timreichen** [comment]
# Goal
Making a deno alternative to webpack, rollup, parcel etc. that does not require node and package.json
# Structure
I am trying to make two things:
- ```Bundler API``` that  bundles deno syntax (url imports, ```.ts``` extensions)  for the web
- ```CLI``` that uses ```Bundler API``` with default settings and plugins to make life as easy as possible (defaults still have to be determined, #5)

# React
Bundler API does not include ```React```. But since it uses ```ts``` compiler API, I think it can be set up to be used for  ```React```. We need a proper react example app instead of example_5.

# Features
- transpiles ts or js modules to ```esm``` modules using ```ts``` compiler API (resolves url imports, ```.ts``` extensions)
- transpiles and bundles modules to ```system``` like ```Deno.bundle``` and include system_loader, but splits code for  dynamically imported modules.
Example:
    ```ts
    // a.ts
    import { b } from "./b.ts" // static import
    console.log(b)
    import("./c.ts") // dynamic import
    ```
     ```ts
    // b.ts
    export const b = "b"
    ```
    ```ts
    // c.ts
    console.log("c")
    ```

    output:
    - dist
      - deps
        - 79e2adc1-f4a8-4c1f-986d-6ca38d777f8f.js (contains transpiled c.ts and system_loader)
      - a.js (contains transpiled a.ts, b.ts and system_loader, imports deps/79e2adc1-f4a8-4c1f-986d-6ca38d777f8f.js dynamically)
- supports css imports
  transpiles ```import styles from "./styles.css"``` to module with string content as default export.
  - in discussion: support css features from stage 3 and css nesting.

## Real world examples
example_3 is a real world example app that uses [lit-element](https://lit-element.polymer-project.org).
Though I agree: The Examples need to be better and labeled properly.

**Comment by itays123** [comment]
Got it, I'm going to make some improvements now. Please approve my pull request

**Comment by itays123** [comment]
just pushed an update documentation.

changes:
- I changed the example
- provided some more info in the beggining 
- added a requirements section.

gonna play around with it so I can provide a big, heavy example.
I would suggest changing the example folder names.

**Comment by timreichen** [comment]
Thank you for your work. I merged it.
I think the requirements section is not necessary because it describes more what we do not need, namely node and package.json.
I updated the examples and restructured the readme to CLI and API sections.

**Comment by timreichen** [comment]
We could use a ```You can use bundler if…``` subsection under ```Why Use Bundler``` to list some use cases.

**Comment by itays123** [comment]
> We could use a ```You can use bundler if…``` subsection under ```Why Use Bundler``` to list some use cases.

Sounds cool, I will keep working on the documentation tomorrow

**Comment by itays123** [comment]
@timreichen what do you think of my last pull?
